spring:
  datasource:
    url: jdbc:mysql://localhost/order-service?&zerodatetimebehavior=Converttonull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: true
  application:
    name: order-service
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30
  client:
    should-unregister-on-shutdown: false


