spring:
  datasource:

    url: jdbc:mysql://localhost:3306/order-service
    username: root
    password: mysql
    initialization-mode: always

  application:
    name: order-service
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
