server:
  port: 8081
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
      default-filters: TokenRelay      
    loadbalancer:
      ribbon:
       enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/microservices-project-realm
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: 3c15c5d0-e1fc-4bff-a8d6-438b5e4a321d
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/spring-cloud-gateway-client
      resourceserver:
        jwt:
         jwt-set-uri: http://localhost:8081/auth/realms/microservices-realm/protocol/openid-connect/certs


            

