server:
  port: 8081
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
    loadbalancer:
      ribbon:
        enabled: false
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/microservices-project-realm
        registration:
          spring-cloud-gateway-client:
            client-id: spring-cloud-gateway-client
            client-secret: 0e669d94-0f80-43bf-8011-64ecb515fdbb
            provider: keycloak
            authorization-grant-type: authorization-code
            redirect-uri: http://localhost:8081/login/oauth2/code/spring-cloud-gateway-client

