spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/inventory-service?&zerodatetimebehavior=Converttonull&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrival=true
  jpa:
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL8Dialect
       ddl-auto: update
   show-sql: true