spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erickjhorman/micro-service-programming-techie
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          clone-on-start: true
server:
  port: 8888
